<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) Contributors to the project

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU Affero General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Affero General Public License for more details.

    You should have received a copy of the GNU Affero General Public License
    along with this program.  If not, see http://www.gnu.org/licenses/.

-->
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>nl.aerius</groupId>
    <artifactId>aerius-root-pom</artifactId>
    <version>1.4.0-SNAPSHOT</version>
    <relativePath /> <!-- lookup parent from repository -->
  </parent>

  <artifactId>gwt-beans-codegen</artifactId>
  <version>1.3.0-SNAPSHOT</version>
  <packaging>pom</packaging>

  <name>GWT Bean Parser Generator</name>
  <description>GWT Bean Parser Generator</description>

  <contributors>
    <contributor>
      <organization>Ministry of Agriculture, Fisheries, Food Security and Nature</organization>
      <organizationUrl>https://www.government.nl/ministries/ministry-of-agriculture-fisheries-food-security-and-nature</organizationUrl>
    </contributor>
  </contributors>

  <scm>
    <connection>scm:git:ssh//git@github.com:aerius/gwt-beans-maven-plugin.git</connection>
    <developerConnection>scm:git:ssh://git@github.com:aerius/gwt-beans-maven-plugin.git</developerConnection>
    <url>https://github.com/aerius/gwt-beans-maven-plugin</url>
  </scm>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>17</maven.compiler.source>
    <maven.compiler.target>17</maven.compiler.target>
  </properties>

  <modules>
    <module>gwt-beans-codegen-test-json</module>
    <module>gwt-beans-codegen-core</module>
    <module>gwt-beans-codegen-maven-plugin</module>
  </modules>

  <dependencyManagement>
    <dependencies>
      <!-- Internal module dependencies -->
      <dependency>
        <groupId>nl.aerius</groupId>
        <artifactId>gwt-beans-codegen-test-json</artifactId>
        <version>${project.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>

  <repositories>
    <repository>
      <id>aerius-nexus-public</id>
      <name>AERIUS Nexus repository</name>
      <url>https://nexus.aerius.nl/repository/maven-public/</url>
      <snapshots>
        <updatePolicy>always</updatePolicy>
      </snapshots>
    </repository>
  </repositories>
  <pluginRepositories>
    <pluginRepository>
      <id>aerius-nexus-public</id>
      <name>AERIUS Nexus Repository</name>
      <url>https://nexus.aerius.nl/repository/maven-public/</url>
      <snapshots>
        <updatePolicy>always</updatePolicy>
      </snapshots>
    </pluginRepository>
  </pluginRepositories>
</project>
